#!/bin/sh
#
# Copy Gemfile.lock to Gemfile.lock.ci.
#
# The Gemfile.lock should not be checked in for a Ruby gem, but it is used by
# circle-ci to save and restore cached bundles. We check-in a copy of the lock
# file that will be ignored by the bundler.
#
# To enable this hook make sure you run the following command:
#
#   prompt> git config core.hooksPath .githooks
#
git_root="$(git rev-parse --show-toplevel)"
gemfile_lock_paths=( $(find "${git_root}" -type f -name 'Gemfile.lock') )

for gemfile_lock in "${gemfile_lock_paths[@]}"
do
    if ! git diff --no-patch --no-index "${gemfile_lock}" "${gemfile_lock}.ci" > /dev/null 2>&1
    then
        cp "${gemfile_lock}" "${gemfile_lock}.ci"
        git add "${gemfile_lock}.ci"
    fi
done
