version: 2

updates:
- package-ecosystem: bundler
  directory: "/"
  schedule:
    interval: daily
    time: "04:00"
    timezone: America/Los_Angeles
  open-pull-requests-limit: 99
  allow:
  - dependency-type: direct
  - dependency-type: indirect
