version: 2
registries:
  rubygems-server-rubygems-pkg-github-com-valimail:
    type: rubygems-server
    url: https://rubygems.pkg.github.com/valimail
    token: "${{secrets.RUBYGEMS_SERVER_RUBYGEMS_PKG_GITHUB_COM_VALIMAIL_TOKEN}}"

updates:
- package-ecosystem: bundler
  directory: "/"
  schedule:
    interval: daily
    time: "04:00"
    timezone: America/Los_Angeles
  open-pull-requests-limit: 99
  allow:
  - dependency-type: direct
  - dependency-type: indirect
  registries:
  - rubygems-server-rubygems-pkg-github-com-valimail
