require:
  - 'rubocop-rails'

AllCops:
  Exclude:
    - 'bin/**/*'
    - 'db/schema.rb'
    - 'spec/rails-app*/**/*'
    - 'vendor/bundle/**/*'
  TargetRubyVersion: 2.4

Metrics/LineLength:
  Enabled: false
Rails:
  Enabled: true
Style/Documentation:
  Enabled: false
Style/FrozenStringLiteralComment:
  Enabled: false
Layout/ExtraSpacing:
  Exclude:
    - 'Gemfile'
    - '*.gemspec'
Lint/UselessAssignment:
  Exclude:
    - 'db/**/*'
Metrics/AbcSize:
  Exclude:
    - 'db/**/*'
Metrics/BlockLength:
  Exclude:
    - '*.gemspec'
    - 'app/models/concerns/**/*'
    - 'config/**/*'
    - 'db/**/*'
    - 'spec/**/*'
Metrics/ClassLength:
  Exclude:
    - 'db/**/*'
Metrics/MethodLength:
  Exclude:
    - 'db/**/*'
Rails/HttpPositionalArguments:
  Include:
    - 'spec/**/*'
Rails/NotNullColumn:
  Exclude:
    - 'db/**/*'
Rails/SkipsModelValidations:
  Exclude:
    - 'spec/**/*'
Style/FormatStringToken:
  EnforcedStyle: template
  SupportedStyles:
    - annotated
    - template
Style/PercentLiteralDelimiters:
  PreferredDelimiters:
    default: '()'
    '%i': '()'
    '%w': '()'
