source 'https://rubygems.org'
git_source(:github) { |repo| "https://github.com/#{repo}.git" }

gem 'bootsnap', '>= 1.1.0', require: false
gem 'coffee-rails', '~> 4.2'
gem 'devise',       '~> 4.0'
gem 'devise-secure_password', path: '../..'
gem 'mini_racer', platforms: :ruby
gem 'puma', '~> 3.11'
gem 'rails', '~> 5.2.0'
gem 'rspec-rails',  '~> 3.7'
gem 'sassc-rails'
gem 'sqlite3'
gem 'uglifier', '>= 1.3.0'

group :development do
  gem 'listen', '>= 3.0.5', '< 3.2'
end

group :test do
  gem 'flay',       '~> 2.10.0'
  gem 'rspec',      '~> 3.7'
  gem 'rubocop',    '~> 0.52.1'
  gem 'ruby2ruby',  '~> 2.4.0'
end

# Windows does not include zoneinfo files, so bundle the tzinfo-data gem
gem 'tzinfo-data', platforms: [:mingw, :mswin, :x64_mingw, :jruby]
