source "https://rubygems.org"

gem 'rails', '~> 5.1.0'
gem 'rake', '~> 12.3'
gem 'sqlite3', '~> 1.3.13'
gem 'sass-rails', '~> 5.0'
gem 'devise', '~> 4.0'
gem 'devise_password_policy_extension', path: '../..'
gem 'rspec-rails', '~> 3.7'
